services:
  - type: web
    name: premierproduct-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3004
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_CLUSTER
        sync: false
      - key: DB_NAME
        value: PremierProducts
      - key: DB_APPNAME
        value: PremierProducts
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CORS_ORIGIN
        sync: false
